language: rust
cache: cargo
sudo: required
script: script/cibuild
rust:
  - nightly
  - beta
  - stable
env:
  - SPEC=false
  - SPEC=true
matrix:
  fast_finish: true
  allow_failures:
    - rust: stable
notifications:
  email:
    on_failure: change
