[package]
name = "comrak"
version = "0.2.6"
authors = ["Ashe Connor <kivikakk@github.com>"]
description = "A 100% CommonMark-compatible GitHub Flavored Markdown parser and formatter"
documentation = "https://docs.rs/comrak"
homepage = "https://github.com/kivikakk/comrak"
repository = "https://github.com/kivikakk/comrak"
readme = "README.md"
keywords = ["markdown", "commonmark"]
license = "BSD-2-Clause"
categories = ["text-processing", "parsing", "command-line-utilities"]

[badges]
travis-ci = { repository = "kivikakk/comrak" }

[profile.release]
lto = true

[[bin]]
name = "comrak"
required-features = ["clap"]
doc = false

[dependencies]
typed-arena = "1.2"
regex = "0.2"
lazy_static = "0.2"
entities = "1.0"
unicode_categories = "0.1"
clap = { version = "2.22", optional = true }
twoway = "0.1"
pest = "1.0.0-rc.1"
pest_derive = "1.0.0-rc.1"

[features]
default = ["clap"]
