name: Rust

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - beta
          - stable
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Build and test
      run: env SPEC=false script/cibuild
    - name: Run spec tests
      run: env SPEC=true script/cibuild
    - name: Install clippy
      run: rustup component add clippy
    - name: Check clippy
      run: cargo clippy
    - name: Check formatting
      run: cargo fmt -- --check
