name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build and test
      run: env SPEC=false script/cibuild
    - name: Run spec tests
      run: env SPEC=true script/cibuild
